export const EMPLOYEE_EVENT_ACTIONS = {
  EMPLOYEE_CREATED: 'EMPLOYEE_CREATED',
  EMPLOYEE_UPDATED: 'EMPLOYEE_UPDATED',
  EMPLOYEE_DEPARTMENT_CHANGED: 'EMPLOYEE_DEPARTMENT_CHANGED',
  EMPLOYEE_STATUS_CHANGED: 'EMPLOYEE_STATUS_CHANGED',
  EMPLOYEE_HIRED: 'EMPLOYEE_HIRED',
  EMPLOYEE_TERMINATED: 'EMPLOYEE_TERMINATED',
  EMPLOYEE_REHIRED: 'EMPLOYEE_REHIRED',
  EMPLOYEE_ROLE_CHANGED: 'EMPLOYEE_ROLE_CHANGED',
  EMPLOYEE_DELETED: 'EMPLOYEE_DELETED',
  ATTENDANCE_CHECKED_IN: 'ATTENDANCE_CHECKED_IN',
  ATTENDANCE_BREAK_OUT: 'ATTENDANCE_BREAK_OUT',
  ATTENDANCE_BREAK_IN: 'ATTENDANCE_BREAK_IN',
  ATTENDANCE_CHECKED_OUT: 'ATTENDANCE_CHECKED_OUT',
  ATTENDANCE_AUTO_CHECKED_OUT: 'ATTENDANCE_AUTO_CHECKED_OUT',
} as const;

export const EMPLOYEE_EVENT_ACTION_LIST = Object.values(EMPLOYEE_EVENT_ACTIONS);

export type EmployeeEventAction =
  (typeof EMPLOYEE_EVENT_ACTIONS)[keyof typeof EMPLOYEE_EVENT_ACTIONS];
