/**
 * 前端权限常量 - 与后端保持同步
 * 用于菜单过滤、功能开关等
 */

export const PERMISSIONS = {
  // Dashboard
  DASHBOARD_VIEW: 'dashboard:view',

  // Organization (仅 sn888xt)
  ORGANIZATION_VIEW: 'organization:view',
  ORGANIZATION_CREATE: 'organization:create',
  ORGANIZATION_EDIT: 'organization:edit',
  ORGANIZATION_DELETE: 'organization:delete',

  // Company
  COMPANY_VIEW: 'company:view',
  COMPANY_EDIT: 'company:edit',
  COMPANY_VIEW_LOGO: 'company:view_logo',
  COMPANY_EDIT_LOGO: 'company:edit_logo',
  COMPANY_VIEW_TIMEZONE: 'company:view_timezone',

  // Teams
  TEAMS_VIEW: 'teams:view',
  TEAMS_CREATE: 'teams:create',
  TEAMS_EDIT: 'teams:edit',
  TEAMS_DELETE: 'teams:delete',

  // Screenshot
  SCREENSHOT_VIEW: 'screenshot:view',
  SCREENSHOT_EXPORT: 'screenshot:export',

  // Attendance
  ATTENDANCE_MANAGE: 'attendance:manage',
  ATTENDANCE_VIEW: 'attendance:view',
  ATTENDANCE_EDIT: 'attendance:edit',
  ATTENDANCE_VIEW_CALENDAR: 'attendance:view_calendar',

  // Shift
  SHIFT_VIEW: 'shift:view',
  SHIFT_CREATE: 'shift:create',
  SHIFT_EDIT: 'shift:edit',
  SHIFT_DELETE: 'shift:delete',

  // Leave
  LEAVE_APPLY: 'leave:apply',
  LEAVE_VIEW: 'leave:view',
  LEAVE_APPROVE: 'leave:approve',
  LEAVE_VIEW_SETTINGS: 'leave:view_settings',
  LEAVE_EDIT_SETTINGS: 'leave:edit_settings',

  // Report
  REPORT_VIEW: 'report:view',
  REPORT_EXPORT: 'report:export',
  REPORT_VIEW_ADVANCED: 'report:view_advanced',

  // Users
  USERS_CREATE: 'users:create',
  USERS_VIEW: 'users:view',
  USERS_EDIT: 'users:edit',
  USERS_DELETE: 'users:delete',

  // Roles
  ROLES_MANAGE: 'roles:manage',
  ROLES_VIEW: 'roles:view',

  // Permissions
  PERMISSIONS_MANAGE: 'permissions:manage',

  // Profile
  PROFILE_VIEW: 'profile:view',
  PROFILE_EDIT: 'profile:edit',

  // Billing (仅 sn888xt)
  BILLING_VIEW: 'billing:view',
  BILLING_EDIT: 'billing:edit',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

/**
 * 系统角色定义
 */
export const SYSTEM_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  COMPANY_ADMIN: 'COMPANY_ADMIN',
  TEAM_LEAD: 'TEAM_LEAD',
  EMPLOYEE: 'EMPLOYEE',
} as const;

export type SystemRole = typeof SYSTEM_ROLES[keyof typeof SYSTEM_ROLES];

/**
 * 角色到权限的映射
 */
export const ROLE_PERMISSIONS_MATRIX: Record<SystemRole, Permission[]> = {
  SUPER_ADMIN: [
    // Dashboard
    PERMISSIONS.DASHBOARD_VIEW,
    // Organization
    PERMISSIONS.ORGANIZATION_VIEW,
    PERMISSIONS.ORGANIZATION_CREATE,
    PERMISSIONS.ORGANIZATION_EDIT,
    PERMISSIONS.ORGANIZATION_DELETE,
    // Company
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.COMPANY_EDIT,
    PERMISSIONS.COMPANY_VIEW_LOGO,
    PERMISSIONS.COMPANY_EDIT_LOGO,
    PERMISSIONS.COMPANY_VIEW_TIMEZONE,
    // Teams
    PERMISSIONS.TEAMS_VIEW,
    PERMISSIONS.TEAMS_CREATE,
    PERMISSIONS.TEAMS_EDIT,
    PERMISSIONS.TEAMS_DELETE,
    // Screenshot
    PERMISSIONS.SCREENSHOT_VIEW,
    PERMISSIONS.SCREENSHOT_EXPORT,
    // Attendance
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_EDIT,
    PERMISSIONS.ATTENDANCE_VIEW_CALENDAR,
    // Shift
    PERMISSIONS.SHIFT_VIEW,
    PERMISSIONS.SHIFT_CREATE,
    PERMISSIONS.SHIFT_EDIT,
    PERMISSIONS.SHIFT_DELETE,
    // Leave
    PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.LEAVE_VIEW,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_VIEW_SETTINGS,
    PERMISSIONS.LEAVE_EDIT_SETTINGS,
    // Report
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_VIEW_ADVANCED,
    // Users
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_EDIT,
    PERMISSIONS.USERS_DELETE,
    // Roles
    PERMISSIONS.ROLES_MANAGE,
    PERMISSIONS.ROLES_VIEW,
    // Permissions
    PERMISSIONS.PERMISSIONS_MANAGE,
    // Profile
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_EDIT,
    // Billing
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.BILLING_EDIT,
  ],
  COMPANY_ADMIN: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.COMPANY_EDIT,
    PERMISSIONS.COMPANY_VIEW_LOGO,
    PERMISSIONS.COMPANY_EDIT_LOGO,
    PERMISSIONS.COMPANY_VIEW_TIMEZONE,
    PERMISSIONS.TEAMS_VIEW,
    PERMISSIONS.TEAMS_CREATE,
    PERMISSIONS.TEAMS_EDIT,
    PERMISSIONS.TEAMS_DELETE,
    PERMISSIONS.SCREENSHOT_VIEW,
    PERMISSIONS.SCREENSHOT_EXPORT,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_EDIT,
    PERMISSIONS.ATTENDANCE_VIEW_CALENDAR,
    PERMISSIONS.SHIFT_VIEW,
    PERMISSIONS.SHIFT_CREATE,
    PERMISSIONS.SHIFT_EDIT,
    PERMISSIONS.SHIFT_DELETE,
    PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.LEAVE_VIEW,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_VIEW_SETTINGS,
    PERMISSIONS.LEAVE_EDIT_SETTINGS,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_VIEW_ADVANCED,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_EDIT,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.ROLES_MANAGE,
    PERMISSIONS.ROLES_VIEW,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_EDIT,
  ],
  TEAM_LEAD: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.TEAMS_VIEW,
    PERMISSIONS.SCREENSHOT_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.ATTENDANCE_VIEW_CALENDAR,
    PERMISSIONS.SHIFT_VIEW,
    PERMISSIONS.LEAVE_VIEW,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_EDIT,
  ],
  EMPLOYEE: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW_CALENDAR,
    PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.LEAVE_VIEW,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_EDIT,
  ],
};
