/**
 * 权限常量定义
 * 权限使用 'module:action' 格式，支持通配符
 */

export const PERMISSIONS = {
  // Dashboard
  DASHBOARD_VIEW: 'dashboard:view',

  // Organization (SuperAdmin only)
  ORGANIZATION_VIEW: 'organization:view',
  ORGANIZATION_CREATE: 'organization:create',
  ORGANIZATION_EDIT: 'organization:edit',
  ORGANIZATION_DELETE: 'organization:delete',

  // Company
  COMPANY_VIEW: 'company:view',
  COMPANY_EDIT: 'company:edit',
  COMPANY_VIEW_LOGO: 'company:view_logo',
  COMPANY_EDIT_LOGO: 'company:edit_logo',
  COMPANY_VIEW_TIMEZONE: 'company:view_timezone',

  // Teams (Workgroups)
  TEAMS_VIEW: 'teams:view',
  TEAMS_CREATE: 'teams:create',
  TEAMS_EDIT: 'teams:edit',
  TEAMS_DELETE: 'teams:delete',

  // Screenshot Wall
  SCREENSHOT_VIEW: 'screenshot:view',
  SCREENSHOT_EXPORT: 'screenshot:export',

  // Attendance
  ATTENDANCE_MANAGE: 'attendance:manage',
  ATTENDANCE_VIEW: 'attendance:view',
  ATTENDANCE_EDIT: 'attendance:edit',
  ATTENDANCE_VIEW_CALENDAR: 'attendance:view_calendar',

  // Shift
  SHIFT_VIEW: 'shift:view',
  SHIFT_CREATE: 'shift:create',
  SHIFT_EDIT: 'shift:edit',
  SHIFT_DELETE: 'shift:delete',

  // Leave
  LEAVE_APPLY: 'leave:apply',
  LEAVE_VIEW: 'leave:view',
  LEAVE_APPROVE: 'leave:approve',
  LEAVE_VIEW_SETTINGS: 'leave:view_settings',
  LEAVE_EDIT_SETTINGS: 'leave:edit_settings',

  // Report
  REPORT_VIEW: 'report:view',
  REPORT_EXPORT: 'report:export',
  REPORT_VIEW_ADVANCED: 'report:view_advanced',

  // Users & Roles
  USERS_CREATE: 'users:create',
  USERS_VIEW: 'users:view',
  USERS_EDIT: 'users:edit',
  USERS_DELETE: 'users:delete',
  ROLES_MANAGE: 'roles:manage',
  ROLES_VIEW: 'roles:view',
  PERMISSIONS_MANAGE: 'permissions:manage',

  // Profile
  PROFILE_VIEW: 'profile:view',
  PROFILE_EDIT: 'profile:edit',

  // Billing
  BILLING_VIEW: 'billing:view',
  BILLING_EDIT: 'billing:edit',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

/**
 * 系统角色定义（固定的 4 个角色）
 */
export const SYSTEM_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  COMPANY_ADMIN: 'COMPANY_ADMIN',
  TEAM_LEAD: 'TEAM_LEAD',
  EMPLOYEE: 'EMPLOYEE',
} as const;

export type SystemRole = typeof SYSTEM_ROLES[keyof typeof SYSTEM_ROLES];

/**
 * 固定角色权限矩阵
 */
export const ROLE_PERMISSIONS_MATRIX: Record<SystemRole, Permission[]> = {
  [SYSTEM_ROLES.SUPER_ADMIN]: [
    // 所有权限
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ORGANIZATION_VIEW,
    PERMISSIONS.ORGANIZATION_CREATE,
    PERMISSIONS.ORGANIZATION_EDIT,
    PERMISSIONS.ORGANIZATION_DELETE,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.COMPANY_EDIT,
    PERMISSIONS.COMPANY_VIEW_LOGO,
    PERMISSIONS.COMPANY_EDIT_LOGO,
    PERMISSIONS.COMPANY_VIEW_TIMEZONE,
    PERMISSIONS.TEAMS_VIEW,
    PERMISSIONS.TEAMS_CREATE,
    PERMISSIONS.TEAMS_EDIT,
    PERMISSIONS.TEAMS_DELETE,
    PERMISSIONS.SCREENSHOT_VIEW,
    PERMISSIONS.SCREENSHOT_EXPORT,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_EDIT,
    PERMISSIONS.ATTENDANCE_VIEW_CALENDAR,
    PERMISSIONS.SHIFT_VIEW,
    PERMISSIONS.SHIFT_CREATE,
    PERMISSIONS.SHIFT_EDIT,
    PERMISSIONS.SHIFT_DELETE,
    PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.LEAVE_VIEW,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_VIEW_SETTINGS,
    PERMISSIONS.LEAVE_EDIT_SETTINGS,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_VIEW_ADVANCED,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_EDIT,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.ROLES_MANAGE,
    PERMISSIONS.ROLES_VIEW,
    PERMISSIONS.PERMISSIONS_MANAGE,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_EDIT,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.BILLING_EDIT,
  ],

  [SYSTEM_ROLES.COMPANY_ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.COMPANY_EDIT,
    PERMISSIONS.COMPANY_VIEW_LOGO,
    PERMISSIONS.COMPANY_EDIT_LOGO,
    PERMISSIONS.COMPANY_VIEW_TIMEZONE,
    PERMISSIONS.TEAMS_VIEW,
    PERMISSIONS.TEAMS_CREATE,
    PERMISSIONS.TEAMS_EDIT,
    PERMISSIONS.TEAMS_DELETE,
    PERMISSIONS.SCREENSHOT_VIEW,
    PERMISSIONS.SCREENSHOT_EXPORT,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_EDIT,
    PERMISSIONS.ATTENDANCE_VIEW_CALENDAR,
    PERMISSIONS.SHIFT_VIEW,
    PERMISSIONS.SHIFT_CREATE,
    PERMISSIONS.SHIFT_EDIT,
    PERMISSIONS.SHIFT_DELETE,
    PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.LEAVE_VIEW,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_VIEW_SETTINGS,
    PERMISSIONS.LEAVE_EDIT_SETTINGS,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_VIEW_ADVANCED,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_EDIT,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.ROLES_MANAGE,
    PERMISSIONS.ROLES_VIEW,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_EDIT,
  ],

  [SYSTEM_ROLES.TEAM_LEAD]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.TEAMS_VIEW,
    PERMISSIONS.SCREENSHOT_VIEW,
    PERMISSIONS.SCREENSHOT_EXPORT,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW_CALENDAR,
    PERMISSIONS.LEAVE_VIEW,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.PROFILE_VIEW,
  ],

  [SYSTEM_ROLES.EMPLOYEE]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW_CALENDAR,
    PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.LEAVE_VIEW,
    PERMISSIONS.PROFILE_VIEW,
  ],
};
